# Database Configuration
db.url=${DB_URL:jdbc:mysql://localhost:3306/atm_db?useSSL=false}
db.username=${DB_USERNAME:root}
db.password=${DB_PASSWORD:2210}

# Mail Configuration (set MAIL_EMAIL and MAIL_PASSWORD as environment variables)
mail.email=${MAIL_EMAIL:}
mail.password=${MAIL_PASSWORD:}

server.port=${PORT:21279}